curl http://localhost:8080/rest/v1/dynamapper/benchmark
curl http://localhost:8080/rest/v1/dynatemplate/benchmark
curl http://localhost:8080/rest/v1/dynamapper/benchmark
curl http://localhost:8080/rest/v1/dynatemplate/benchmark
curl http://localhost:8080/rest/v1/dynamapper/benchmark
curl http://localhost:8080/rest/v1/dynatemplate/benchmark
curl http://localhost:8080/rest/v1/dynamapper/benchmark
curl http://localhost:8080/rest/v1/dynatemplate/benchmark
curl http://localhost:8080/rest/v1/dynamapper/benchmark
curl http://localhost:8080/rest/v1/dynatemplate/benchmark
curl http://localhost:8080/rest/v1/dynamapper/benchmark
curl http://localhost:8080/rest/v1/dynatemplate/benchmark
curl http://localhost:8080/rest/v1/dynamapper/benchmark
curl http://localhost:8080/rest/v1/dynatemplate/benchmark
curl http://localhost:8080/rest/v1/dynamapper/benchmark
curl http://localhost:8080/rest/v1/dynatemplate/benchmark
curl http://localhost:8080/rest/v1/dynamapper/benchmark
curl http://localhost:8080/rest/v1/dynatemplate/benchmark
curl http://localhost:8080/rest/v1/dynamapper/benchmark
curl http://localhost:8080/rest/v1/dynatemplate/benchmark